### ISSUE TITLE
Bad docs and need more proper method name for Templator::widgets() in order to be more representing its concern

### ISSUE THREAD

**Issue by okaprinarjaya** [Kristories/Templator#4]
Hi @Kristories ,

I interested with your Templator project, after doing some testing i think it's a light and simple solution for a developer to get the flexibility to consume and adjust layout provided by template designer.

But,  your project doesn't have good documentation. You need to provide better documentation. 

And, after i browse your codebase, i think method Templator::widgets() not just preparing the widgets, the method also preparing the positions. 
i think you need more proper method name that can more representing the method's concern. I understand what is your Templator::widgets() want to do.

I have an idea and proposing to you a proper method name, following is method name that i propose to you:
- Templator::arrange()
- Templator::blocks()

**Comment by Kristories** [comment]
`blocks()` hear good method name. I'll try..

**Comment by Kristories** [comment]
Method name changed
